// <auto-generated />
using System;
using MediathekNext.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediathekNext.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MediathekNext.Domain.Entities.AppSettings", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<int>("CatalogRefreshIntervalHours").HasColumnType("INTEGER");
                b.Property<string>("CatalogProviderKey").IsRequired().HasColumnType("TEXT");
                b.Property<string>("DownloadDirectory").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.Property<int>("MaxConcurrentDownloads").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.ToTable("Settings");
                b.HasData(new { Id = 1, CatalogRefreshIntervalHours = 6, CatalogProviderKey = "mediathekview", DownloadDirectory = "/downloads", MaxConcurrentDownloads = 2 });
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.Channel", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("ProviderKey").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Channels");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.DownloadJob", b =>
            {
                b.Property<Guid>("Id").HasColumnType("TEXT");
                b.Property<string>("CompletedAt").HasColumnType("TEXT");
                b.Property<string>("CreatedAt").IsRequired().HasColumnType("TEXT");
                b.Property<string>("EpisodeId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnType("TEXT");
                b.Property<long?>("FileSizeBytes").HasColumnType("INTEGER");
                b.Property<string>("OutputPath").HasMaxLength(1000).HasColumnType("TEXT");
                b.Property<double?>("ProgressPercent").HasColumnType("REAL");
                b.Property<string>("Quality").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                b.Property<string>("StreamUrl").IsRequired().HasMaxLength(2000).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("CreatedAt").HasDatabaseName("IX_DownloadJobs_CreatedAt");
                b.HasIndex("Status").HasDatabaseName("IX_DownloadJobs_Status");
                b.ToTable("DownloadJobs");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.Episode", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("AvailableUntil").HasColumnType("TEXT");
                b.Property<string>("BroadcastDate").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ContentType").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Description").HasMaxLength(5000).HasColumnType("TEXT");
                b.Property<double>("Duration").HasColumnType("REAL");
                b.Property<string>("ShowId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("BroadcastDate").HasDatabaseName("IX_Episodes_BroadcastDate");
                b.HasIndex("ContentType").HasDatabaseName("IX_Episodes_ContentType");
                b.HasIndex("ShowId").HasDatabaseName("IX_Episodes_ShowId");
                b.ToTable("Episodes");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.EpisodeStream", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("EpisodeId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Format").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<string>("Quality").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Url").IsRequired().HasMaxLength(2000).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("EpisodeId").HasDatabaseName("IX_EpisodeStreams_EpisodeId");
                b.ToTable("EpisodeStreams");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.Show", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("ChannelId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ChannelId");
                b.ToTable("Shows");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.DownloadJob", b =>
            {
                b.HasOne("MediathekNext.Domain.Entities.Episode", "Episode")
                    .WithMany()
                    .HasForeignKey("EpisodeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Episode");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.Episode", b =>
            {
                b.HasOne("MediathekNext.Domain.Entities.Show", "Show")
                    .WithMany("Episodes")
                    .HasForeignKey("ShowId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Show");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.EpisodeStream", b =>
            {
                b.HasOne("MediathekNext.Domain.Entities.Episode", null)
                    .WithMany("Streams")
                    .HasForeignKey("EpisodeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.Show", b =>
            {
                b.HasOne("MediathekNext.Domain.Entities.Channel", "Channel")
                    .WithMany()
                    .HasForeignKey("ChannelId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Channel");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.Episode", b =>
            {
                b.Navigation("Streams");
            });

            modelBuilder.Entity("MediathekNext.Domain.Entities.Show", b =>
            {
                b.Navigation("Episodes");
            });
#pragma warning restore 612, 618
        }
    }
}
