// <auto-generated />
using System;
using Krautwatch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Krautwatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809024027_AddEpisodeSubtitleUrl")]
    partial class AddEpisodeSubtitleUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Krautwatch.Domain.Entities.AdminAccount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AdminAccounts");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogRefreshIntervalHours")
                        .HasColumnType("integer");

                    b.Property<string>("DownloadDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EgressProxyListEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("EgressProxyListMaxCandidates")
                        .HasColumnType("integer");

                    b.Property<string>("EgressProxyUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxConcurrentDownloads")
                        .HasColumnType("integer");

                    b.Property<string>("SearchWaitMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SearchWaitSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SetupCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TvdbApiKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatalogRefreshIntervalHours = 6,
                            DownloadDirectory = "/downloads",
                            EgressProxyListEnabled = false,
                            EgressProxyListMaxCandidates = 5,
                            MaxConcurrentDownloads = 2,
                            SearchWaitMode = "ReturnFast",
                            SearchWaitSeconds = 8
                        });
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.ArrInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastTestMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("LastTestOk")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUrl")
                        .IsUnique();

                    b.ToTable("ArrInstances");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.DownloadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("text");

                    b.Property<long?>("ContentLengthBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EpisodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("GeoRestricted")
                        .HasColumnType("boolean");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double?>("ProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleaseName")
                        .HasColumnType("text");

                    b.Property<string>("StartedAt")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TempPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "Priority", "CreatedAt")
                        .HasDatabaseName("IX_DownloadJobs_Queue");

                    b.ToTable("DownloadJobs");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.Episode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("AbsoluteEpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("AvailableUntil")
                        .HasColumnType("text");

                    b.Property<string>("BroadcastDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("GeoRestricted")
                        .HasColumnType("boolean");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ShowId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubtitleUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BroadcastDate");

                    b.HasIndex("ContentType");

                    b.HasIndex("ShowId");

                    b.HasIndex("ShowId", "SeasonNumber", "EpisodeNumber");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.EpisodeStream", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EpisodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.ToTable("EpisodeStreams");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.ImportedShowHint", b =>
                {
                    b.Property<int>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedTopic")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("TvdbId", "NormalizedTopic");

                    b.HasIndex("Source");

                    b.HasIndex("TvdbId");

                    b.ToTable("ImportedShowHints");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.Proxy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AnonymityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("LastProbeOk")
                        .HasColumnType("boolean");

                    b.Property<string>("LastProbedAt")
                        .HasColumnType("text");

                    b.Property<double>("Latency")
                        .HasColumnType("double precision");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ResponseTime")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceLastChecked")
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<double>("UpTime")
                        .HasColumnType("double precision");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerifiedEgressCountry")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.ToTable("Proxies");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.ResolvedQuery", b =>
                {
                    b.Property<string>("Query")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProvidersTried")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer");

                    b.HasKey("Query");

                    b.ToTable("ResolvedQueries");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.Show", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeriesType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.ShowMapping", b =>
                {
                    b.Property<int>("TvdbId")
                        .HasColumnType("integer");

                    b.Property<string>("ShowId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastPickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PickCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TvdbId", "ShowId");

                    b.HasIndex("ShowId")
                        .IsUnique();

                    b.HasIndex("TvdbId");

                    b.ToTable("ShowMappings");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.DownloadJob", b =>
                {
                    b.HasOne("Krautwatch.Domain.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.Episode", b =>
                {
                    b.HasOne("Krautwatch.Domain.Entities.Show", "Show")
                        .WithMany("Episodes")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.EpisodeStream", b =>
                {
                    b.HasOne("Krautwatch.Domain.Entities.Episode", null)
                        .WithMany("Streams")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.Show", b =>
                {
                    b.HasOne("Krautwatch.Domain.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.ShowMapping", b =>
                {
                    b.HasOne("Krautwatch.Domain.Entities.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.Episode", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("Krautwatch.Domain.Entities.Show", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
