<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.1.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Migrator\Krautwatch.Migrator.csproj" />
    <ProjectReference Include="..\Api\NewznabIndexerApi\Krautwatch.Api.NewznabIndexerApi.csproj" />
    <ProjectReference Include="..\Web\Krautwatch.Web.csproj" />
    <ProjectReference Include="..\Agents\Ard\Krautwatch.Agents.Ard.csproj" />
    <ProjectReference Include="..\Agents\Zdf\Krautwatch.Agents.Zdf.csproj" />
    <ProjectReference Include="..\Agents\Downloader\Krautwatch.Agents.Downloader.csproj" />
  </ItemGroup>

</Project>
